### ISSUE TITLE
Is run-node a missing dependency?

### ISSUE THREAD

**Issue by tillsanders** [Cloudstek/alfred-hugo#6]
Whenever I try to run my workflow, I get the error message: `./node_modules/.bin/run-node: No such file or directory`. Interestingly, Hugo works, as long as alfy is installed (installed, but not even imported). So, I discovered, there actually is a package named `run-node` and my workflow works, when I install it. Which leads me to my question: is `node-run` a dependency of Hugo that is missing from the package.json?

**Hugo version:** 2.0.5
**Alfred version:** 4.0.8
**NodeJS version:** 12.16.0

**Comment by mdeboer** [comment]
Hi @tillsanders, no the package `run-node` is not a dependency of Hugo. What happens if you run `yarn why run-node`?

**Comment by tillsanders** [comment]
I investigated further. Turned out, it was my mistake. I used this line to run the script filter in my workflow: 

`./node_modules/.bin/run-node index.js "$1"`

 😅 Sry about the fuss.

Is there a recommended way of running node when using alfred-hugo? I've seen, the alfred-atom package does it like [this](https://github.com/Cloudstek/alfred-atom/blob/master/info.plist#L107):

`${nodePath:-/usr/local/bin/node} dist/index.js projects`

This obviously doesn't require another dependency, but is it cross-plattform compatible?

**Comment by mdeboer** [comment]
Alfred is MacOS only so probably not, but if it were, you would be able to set the nodePath variable yourself in the workflow details to whatever path.

**Comment by tillsanders** [comment]
Oh. Yes, you're right 😅 I completely forgot about that. Hm. That makes my issue completely unnecessary 😄
